-- =============================================================================
-- PocketSmart AI  -  Supabase (PostgreSQL) schema
-- =============================================================================
-- HOW TO RUN
--   Supabase Dashboard -> SQL Editor -> New query -> paste this whole file -> Run.
--   It is idempotent: running it again is safe (nothing is dropped or reset,
--   except the RLS policies, which are re-created).
--
-- HOW THE APP USES THIS DATABASE
--   The FastAPI backend has its own authentication (bcrypt + JWT + server-side
--   sessions), so it does NOT use Supabase Auth or the Supabase Data API.  It
--   connects straight to Postgres with the connection string in DATABASE_URL
--   (role "postgres", which bypasses Row Level Security).
--
--   Because Supabase exposes every table in the "public" schema through the
--   Data API (PostgREST) to the `anon` / `authenticated` roles, the tables below
--   are locked down so the publishable key can never read them:
--     1. Row Level Security is ENABLED on every table,
--     2. an explicit deny-all policy exists for `anon` and `authenticated`,
--     3. every table / sequence privilege is REVOKED from those two roles.
--   (`service_role`, i.e. the Secret key, bypasses RLS by design - keep it
--    server-side only.)
--
-- COLUMN TYPES
--   created_at / login_time / last_activity / expires_at / timestamp are stored
--   as ISO-8601 UTC text (e.g. 2026-10-03T06:27:00.123456+00:00), exactly as the
--   application writes and compares them.  They sort correctly as text, so the
--   column types intentionally match the application models.
-- =============================================================================

begin;

-- -----------------------------------------------------------------------------
-- users
-- -----------------------------------------------------------------------------
create table if not exists public.users (
    id               integer generated by default as identity primary key,
    username         varchar(64)  not null,
    email            varchar(254),
    full_name        varchar(120),
    hashed_password  varchar(255) not null,
    disabled         boolean      not null default false,
    created_at       varchar(40)  not null,
    constraint users_username_not_blank check (char_length(btrim(username)) > 0),
    constraint users_email_not_blank    check (email is null or char_length(btrim(email)) > 0)
);

-- Case-insensitive uniqueness (the app looks users up with lower(username)).
-- Several users may have no e-mail: NULLs never collide in a unique index.
create unique index if not exists uq_users_username_lower on public.users (lower(username));
create unique index if not exists uq_users_email_lower    on public.users (lower(email));

-- -----------------------------------------------------------------------------
-- recommendations  (saved plans / history)
-- -----------------------------------------------------------------------------
create table if not exists public.recommendations (
    id           varchar(36)      primary key,                       -- uuid4 string
    user_id      integer          not null
                                  references public.users (id) on delete cascade,
    category     varchar(20)      not null,
    budget       double precision not null,
    preferences  text             not null,                          -- JSON text
    result       text             not null,                          -- JSON text
    "timestamp"  varchar(40)      not null,
    constraint recommendations_category_valid check (category in ('home', 'party', 'jewelry')),
    constraint recommendations_budget_positive check (budget > 0)
);

-- History page: WHERE user_id = ? ORDER BY timestamp DESC
create index if not exists recommendations_user_time
    on public.recommendations (user_id, "timestamp" desc);

-- -----------------------------------------------------------------------------
-- sessions  (one row per issued access token, keyed by the JWT "jti" claim)
-- -----------------------------------------------------------------------------
create table if not exists public.sessions (
    id             varchar(36) primary key,
    user_id        integer     not null
                               references public.users (id) on delete cascade,
    login_time     varchar(40) not null,
    last_activity  varchar(40) not null,
    expires_at     varchar(40) not null,
    revoked        boolean     not null default false,
    user_data      text        not null default '{}'                 -- JSON text
);

create index if not exists sessions_user          on public.sessions (user_id);
-- Background clean-up deletes by expires_at / last_activity every 5 minutes.
create index if not exists sessions_expires_at    on public.sessions (expires_at);
create index if not exists sessions_last_activity on public.sessions (last_activity);

-- -----------------------------------------------------------------------------
-- Row Level Security
-- -----------------------------------------------------------------------------
alter table public.users           enable row level security;
alter table public.recommendations enable row level security;
alter table public.sessions        enable row level security;

-- Explicit deny-all for the two roles that the Data API / publishable key uses.
-- (With RLS on and no policy Postgres already denies access; the policies make
--  the intent explicit and silence the "RLS enabled, no policy" advisor note.)
drop policy if exists users_deny_client_access           on public.users;
drop policy if exists recommendations_deny_client_access on public.recommendations;
drop policy if exists sessions_deny_client_access        on public.sessions;

create policy users_deny_client_access
    on public.users for all to anon, authenticated
    using (false) with check (false);

create policy recommendations_deny_client_access
    on public.recommendations for all to anon, authenticated
    using (false) with check (false);

create policy sessions_deny_client_access
    on public.sessions for all to anon, authenticated
    using (false) with check (false);

-- Defence in depth: remove the default Supabase grants as well.
revoke all on table public.users           from anon, authenticated;
revoke all on table public.recommendations from anon, authenticated;
revoke all on table public.sessions        from anon, authenticated;
revoke all on sequence public.users_id_seq from anon, authenticated;

commit;

-- =============================================================================
-- VERIFY (optional): run these after the script.
-- =============================================================================
-- 1) All three tables exist and RLS is on (rowsecurity = true):
--      select tablename, rowsecurity from pg_tables
--      where schemaname = 'public' and tablename in ('users','recommendations','sessions');
--
-- 2) Policies are in place:
--      select tablename, policyname, roles, cmd from pg_policies where schemaname = 'public';
--
-- 3) The publishable key cannot read anything (must return 0 privileges):
--      select grantee, table_name, privilege_type
--      from information_schema.role_table_grants
--      where table_schema = 'public' and grantee in ('anon','authenticated');
